name: New device request
description: Request support for a new Teltonika device model.
title: "[Device]: <model>"
labels: ["new device"]
assignees: []

body:
  - type: dropdown
    id: device_type
    attributes:
      label: Device type
      description: Select the type of Teltonika device.
      options:
        - Router
        - Gateway
        - Access Point
        - Switch
    validations:
      required: true

  - type: input
    id: device_model
    attributes:
      label: Device model
      description: Provide the exact model (e.g., RUT240, RUT955, RUTX11).
      placeholder: "RUTX11"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional details (optional)
      description: Add context if relevant (e.g., firmware version, special features, use case).
      placeholder: "Optional notes..."
    validations:
      required: false
