from ...endpoints import *
from .switch import Switch


class TSW212(Switch):
    def __init__(self, base_url: str, *, timeout: float = 10.0, verify: bool = True) -> None:
        super().__init__(base_url, timeout=timeout, verify=verify)

        self.troubleshoot = Troubleshoot(self._client)
        self.diagnostics = Diagnostics(self._client)
        self.logging = Logging(self._client)
        self.macfilter = MACFilter(self._client)
        self.users = Users(self._client)
        self.firmware = Firmware(self._client)
        self.fota = FOTA(self._client)
        self.opc_ua = OPCUA(self._client)
        self.backup = Backup(self._client)
        self.integrity = Integrity(self._client)
        self.mrp = MRP(self._client)
        self.forwarding_table = ForwardingTable(self._client)
        self.two_fa_login = TwoFALogin(self._client)
        self.two_fa = TwoFA(self._client)
        self.sso_login = SSOLogin(self._client)
        self.sso = SSO(self._client)
        self.ip_neighbors = IPNeighbors(self._client)
        self.ip_routes = IPRoutes(self._client)
        self.snmp = SNMP(self._client)
        self.qos = QoS(self._client)
        self.link_aggregation = LinkAggregation(self._client)
        self.package_manager = PackageManager(self._client)
        self.port_based_vlan = PortBasedVlan(self._client)
        self.stp = STP(self._client)
        self.profiles = Profiles(self._client)
        self.iec_60870_5_client = IEC608705Client(self._client)
        self.topology = Topology(self._client)
        self.profinet = Profinet(self._client)
        self.iec_60870_5_server = IEC608705Server(self._client)
        self.rms = RMS(self._client)
        self.ethernet_ip = EthernetIP(self._client)
        self.events_log = EventsLog(self._client)
        self.ospf = OSPF(self._client)
        self.interfaces = Interfaces(self._client)
        self.system = System(self._client)
        self.eigrp = EIGRP(self._client)
        self.access_control = AccessControl(self._client)
        self.ports_settings = PortsSettings(self._client)
        self.rip = RIP(self._client)
        self.password_policy = PasswordPolicy(self._client)
        self.dhcp_relay = DHCPRelay(self._client)
        self.dhcp_servers = DHCPServers(self._client)
        self.bgp = BGP(self._client)
        self.port_mirroring = PortMirroring(self._client)
        self.lldp = LLDP(self._client)
        self.dot1x = Dot1X(self._client)
        self.site_manager_client_status = SiteManagerClientStatus(self._client)
        self.modbus = Modbus(self._client)
        self.universal_gateway = UniversalGateway(self._client)
        self.network = Network(self._client)
        self.wake_on_lan = WakeOnLan(self._client)
        self.loopback = Loopback(self._client)
        self.cable_diagnostic = CableDiagnostic(self._client)
        self.auto_reboot = AutoReboot(self._client)
        self.date_time = DateTime(self._client)
        self.ports = Ports(self._client)
        self.unauthorized = Unauthorized(self._client)
        self.authentication = Authentication(self._client)
