import ssl

from ...endpoints import *
from .router import Router


class ATRM50(Router):
    def __init__(self, base_url: str, *, timeout: float = 10.0, verify: bool | ssl.SSLContext = True) -> None:
        super().__init__(base_url, timeout=timeout, verify=verify)

        self.apn_database = APNDatabase(self._client)
        self.aws = AWS(self._client)
        self.bacnet = Bacnet(self._client)
        self.bfd = BFD(self._client)
        self.bonding = Bonding(self._client)
        self.call_utilities = CallUtilities(self._client)
        self.console = Console(self._client)
        self.data_limit = DataLimit(self._client)
        self.data_usage = DataUsage(self._client)
        self.dfota = DFOTA(self._client)
        self.dhcp_relay = DHCPRelay(self._client)
        self.dlna = DLNA(self._client)
        self.dot1x = Dot1X(self._client)
        self.eoip = EoIP(self._client)
        self.esim = eSIM(self._client)
        self.event_juggler = EventJuggler(self._client)
        self.gps = GPS(self._client)
        self.hotspot_2 = Hotspot2(self._client)
        self.iec_60870_5_client = IEC608705Client(self._client)
        self.iec_60870_5_server = IEC608705Server(self._client)
        self.impulse_counter = ImpulseCounter(self._client)
        self.input_output = InputOutput(self._client)
        self.integrity = Integrity(self._client)
        self.internet_connection = InternetConnection(self._client)
        self.itxpt = ITxPT(self._client)
        self.ldp = LDP(self._client)
        self.messages = Messages(self._client)
        self.modem_control = ModemControl(self._client)
        self.modems = Modems(self._client)
        self.nat64 = NAT64(self._client)
        self.network = Network(self._client)
        self.network_usage = NetworkUsage(self._client)
        self.ntrip = NTRIP(self._client)
        self.openconnect = OpenConnect(self._client)
        self.operator_lists = OperatorLists(self._client)
        self.ospfv3 = OSPFv3(self._client)
        self.overip = OverIP(self._client)
        self.password_policy = PasswordPolicy(self._client)
        self.port_based_vlan = PortBasedVlan(self._client)
        self.port_mirroring = PortMirroring(self._client)
        self.ports_settings = PortsSettings(self._client)
        self.power_control = PowerControl(self._client)
        self.qos = QoS(self._client)
        self.relayd = Relayd(self._client)
        self.samba = Samba(self._client)
        self.sd_usb_tools = SDUSBTools(self._client)
        self.serial = Serial(self._client)
        self.sim_cards = SIMCards(self._client)
        self.sim_idle_protection = SIMIdleProtection(self._client)
        self.sim_switch = SIMSwitch(self._client)
        self.sim_switch_log = SIMSwitchLog(self._client)
        self.sim_switch_status = SIMSwitchStatus(self._client)
        self.site_manager_client_status = SiteManagerClientStatus(self._client)
        self.smcroute = SMCRoute(self._client)
        self.smpp = SMPP(self._client)
        self.sms_gateway = SMSGateway(self._client)
        self.sms_utilities = SMSUtilities(self._client)
        self.sqm = SQM(self._client)
        self.sso = SSO(self._client)
        self.sso_login = SSOLogin(self._client)
        self.starlink = Starlink(self._client)
        self.tailscale = Tailscale(self._client)
        self.traffic_logging = TrafficLogging(self._client)
        self.two_fa = TwoFA(self._client)
        self.two_fa_login = TwoFALogin(self._client)
        self.udp_broadcast_relay = UDPBroadcastRelay(self._client)
        self.universal_gateway = UniversalGateway(self._client)
        self.vrf = VRF(self._client)
        self.vrrp = VRRP(self._client)
        self.wfq = WFQ(self._client)
        self.wifi_scanner = WiFiScanner(self._client)
        self.wireless = Wireless(self._client)
